In [70]:
with open('glove.6B/glove.6B.50d.txt', 'r', encoding='utf-8') as f:
    print(f.readline())

the 0.418 0.24968 -0.41242 0.1217 0.34527 -0.044457 -0.49688 -0.17862 -0.00066023 -0.6566 0.27843 -0.14767 -0.55677 0.14658 -0.0095095 0.011658 0.10204 -0.12792 -0.8443 -0.12181 -0.016801 -0.33279 -0.1552 -0.23131 -0.19181 -1.8823 -0.76746 0.099051 -0.42125 -0.19526 4.0071 -0.18594 -0.52287 -0.31681 0.00059213 0.0074449 0.17778 -0.15897 0.012041 -0.054223 -0.29871 -0.15749 -0.34758 -0.045637 -0.44251 0.18785 0.0027849 -0.18411 -0.11514 -0.78581



In [71]:
with open('glove.6B/glove.6B.50d.txt', 'r', encoding='utf-8') as f:
    print(len(f.readlines()))

400000


In [72]:
embeddings_list = []
word_to_index = {}

with open('glove.6B/glove.6B.50d.txt', 'r', encoding='utf-8') as f:

    #Iterate through each line in the file
    for index,line in enumerate(f):

        #Split the line by whitespace to separate the word and its embedding vector
        values = line.split()

        #Extract the word
        word = values[0]

        #Extract the embedding vector as a list of floats
        embedding = list(map(float, values[1:]))

        #Add the word and its corresponding index to the dictionary
        word_to_index[word] = index

        #Add the embedding vector to the list
        embeddings_list.append(embedding)

In [73]:
print(embeddings_list[word_to_index['butterfly']])

[-0.044005, 0.77475, -0.77523, 1.4307, 0.13771, 0.45879, 0.56295, -0.50569, 1.657, -0.75087, -0.049541, -0.52203, 0.8091, 0.16592, 1.1114, -0.52922, 0.40712, 0.053937, -1.6479, -1.148, -0.82796, -0.43042, 0.23661, -0.11981, 1.1127, -0.33138, -0.25964, 0.082442, -0.86581, -0.36848, 0.66796, -0.32274, -0.11277, 0.4898, -1.195, -0.38779, 0.65561, 0.67454, -0.65664, -0.669, 0.45747, -0.26985, 0.63983, 0.69449, 0.73995, 0.12497, 0.16706, -2.0722, -0.14311, -0.46015]


In [74]:
print(embeddings_list[word_to_index['flower']])

[0.075439, 1.2659, -1.3179, 0.11341, 1.4513, 0.17337, -0.56265, -1.0706, 0.54898, 0.30163, -0.11471, 0.38498, 0.9205, -0.2491, 0.3308, 0.060113, -0.0068846, 0.086864, -0.20535, -0.86098, 0.10007, -0.75486, 0.48225, -0.33253, -0.23791, 0.17345, 0.49777, 0.88761, 0.089471, -0.56217, 1.8535, -0.0055493, 0.45845, 0.53943, 0.3247, 0.43479, -0.027253, 0.44744, -0.27514, -0.016152, -0.51024, -0.10113, -0.80985, -0.31571, 1.5817, 0.2105, -0.1844, -1.7266, 0.092685, -0.55696]


In [75]:
print(embeddings_list[word_to_index['honey']])

[-0.019985, 0.53935, -0.90326, 0.090016, 0.29855, 0.32611, -0.50857, 0.10907, 0.33927, 0.5704, 0.25034, 1.04, 1.343, -0.60772, 0.40619, 0.27913, 0.32208, 0.38446, -0.29457, -0.69277, 0.14046, -0.82279, 2.0253, 0.27792, 0.078601, -0.20447, -0.88572, 0.78072, 0.97837, -0.71111, 1.1592, -0.02509, -0.44024, 1.1104, 0.35465, -0.12271, -0.85505, -0.045262, 1.1047, -0.48242, 0.25227, -0.029808, -0.66215, -0.81188, 1.341, 0.48851, 0.13514, -0.63677, -0.060598, 0.020401]


In [76]:
import torch.nn as nn
embedding = nn.Embedding(5,3)

In [77]:
indices = torch.LongTensor([0,3])
embedding(indices)

tensor([[ 1.2555, -0.5793,  0.7696],
        [ 1.3860, -1.0305, -0.2780]], grad_fn=<EmbeddingBackward0>)

In [78]:
import torch
embeddings_tensor = torch.FloatTensor(embeddings_list)
embedding = nn.Embedding.from_pretrained(embeddings_tensor)
print(embedding)

Embedding(400000, 50)


In [79]:
indices = torch.LongTensor([word_to_index['butterfly']])
print(embedding(indices))

tensor([[-0.0440,  0.7747, -0.7752,  1.4307,  0.1377,  0.4588,  0.5630, -0.5057,
          1.6570, -0.7509, -0.0495, -0.5220,  0.8091,  0.1659,  1.1114, -0.5292,
          0.4071,  0.0539, -1.6479, -1.1480, -0.8280, -0.4304,  0.2366, -0.1198,
          1.1127, -0.3314, -0.2596,  0.0824, -0.8658, -0.3685,  0.6680, -0.3227,
         -0.1128,  0.4898, -1.1950, -0.3878,  0.6556,  0.6745, -0.6566, -0.6690,
          0.4575, -0.2698,  0.6398,  0.6945,  0.7400,  0.1250,  0.1671, -2.0722,
         -0.1431, -0.4602]])


In [83]:
input_string = "The cat loves to drink milk"
tokens = input_string.lower().split()
indices = torch.LongTensor([word_to_index[token] for token in tokens])
print(embedding(indices).shape)
print(embedding(indices))

torch.Size([6, 50])
tensor([[ 4.1800e-01,  2.4968e-01, -4.1242e-01,  1.2170e-01,  3.4527e-01,
         -4.4457e-02, -4.9688e-01, -1.7862e-01, -6.6023e-04, -6.5660e-01,
          2.7843e-01, -1.4767e-01, -5.5677e-01,  1.4658e-01, -9.5095e-03,
          1.1658e-02,  1.0204e-01, -1.2792e-01, -8.4430e-01, -1.2181e-01,
         -1.6801e-02, -3.3279e-01, -1.5520e-01, -2.3131e-01, -1.9181e-01,
         -1.8823e+00, -7.6746e-01,  9.9051e-02, -4.2125e-01, -1.9526e-01,
          4.0071e+00, -1.8594e-01, -5.2287e-01, -3.1681e-01,  5.9213e-04,
          7.4449e-03,  1.7778e-01, -1.5897e-01,  1.2041e-02, -5.4223e-02,
         -2.9871e-01, -1.5749e-01, -3.4758e-01, -4.5637e-02, -4.4251e-01,
          1.8785e-01,  2.7849e-03, -1.8411e-01, -1.1514e-01, -7.8581e-01],
        [ 4.5281e-01, -5.0108e-01, -5.3714e-01, -1.5697e-02,  2.2191e-01,
          5.4602e-01, -6.7301e-01, -6.8910e-01,  6.3493e-01, -1.9726e-01,
          3.3685e-01,  7.7350e-01,  9.0094e-01,  3.8488e-01,  3.8367e-01,
          2.6570e